### ISSUE TITLE
Initial Build

### ISSUE THREAD

**Issue by benjamingregory** [aries-data/aries-activity-adwords-source#1]
**Requirements**
- Allow user to pass in AWQL (Adwords Query Language) as part of request
- Allow user to specify return format
- Include `method` parameter which is defaulted to `AWQL` but can be set to execute a method that prefills a report call
- Include [`date range`](https://developers.google.com/adwords/api/docs/guides/reporting#date_ranges) parameter. Default to past day
  - Allow for [custom range](https://developers.google.com/adwords/api/docs/guides/reporting#custom_date_ranges) in date parameter
- Set `WHERE Status IN [ENABLED, PAUSED]` as a default element of all queries.
- Create report methods pulling all fields for the following.:
  - [ ] [Keywords Performance](https://developers.google.com/adwords/api/docs/appendix/reports/keywords-performance-report)
  - [ ] [Criteria Performance](https://developers.google.com/adwords/api/docs/appendix/reports/criteria-performance-report)
  - [ ] [Gender Performance](https://developers.google.com/adwords/api/docs/appendix/reports/gender-performance-report)
  - [ ] [Age Range Performance](https://developers.google.com/adwords/api/docs/appendix/reports/age-range-performance-report)
  - [ ] [Placement Performance](https://developers.google.com/adwords/api/docs/appendix/reports/placement-performance-report)
  - [ ] [Geo Performance](https://developers.google.com/adwords/api/docs/appendix/reports/geo-performance-report) 
  - [ ] [Account Performance](https://developers.google.com/adwords/api/docs/appendix/reports/account-performance-report)
  - [ ] [Campaign Performance](https://developers.google.com/adwords/api/docs/appendix/reports/campaign-performance-report)
- Include `attribution` parameter that can be used in Keywords and Criteria Performance reports

**Relevant Links**
https://developers.google.com/adwords/api/docs/guides/reporting
https://developers.google.com/adwords/api/docs/guides/awql#using_awql_with_reports
https://developers.google.com/adwords/api/docs/guides/reporting#supported_download_formats
https://developers.google.com/adwords/api/docs/appendix/reports/gender-performance-report

**Comment by benjamingregory** [comment]
From Thomas: 
"Only feature not supported is attribution - I couldn't figure out what AWQL parameter correlated w/ it"

Also needs Mocha tests

**Comment by benjamingregory** [comment]
@undercase Are attribution and mocha tests still the only elements that need to be added?

**Comment by byerc** [comment]
Beginning to digest this today. Starting with swapping blue-tape with mocha.

**Comment by beckysteele** [comment]
Putting this in the icebox for now @byerc.  Will handoff to someone else when future implementations require it.
